/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p47.reto4;

import java.text.DecimalFormat;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import utp.misiontic2022.c2.p47.reto4.modelo.vo.Lider;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.PromedioSalario;
import utp.misiontic2022.c2.p47.reto4.vista.VistaRequerimientosReto4;

/**
 *
 * @author ladym
 */
public class GUI_Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Proyecto
     */
    public GUI_Proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Definicion de jpane
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Proyecto Construcción");

        // Se trae informacion de lider
        ArrayList<Lider> informacionLider = VistaRequerimientosReto4.requerimiento1();

        // Se trae informacion nombre Lider
        ArrayList<String> nombresLideres = VistaRequerimientosReto4.requerimiento2();

        // Se trae informacion de cargos y promedio salarios
        ArrayList<PromedioSalario> promediosSalarios = VistaRequerimientosReto4.requerimiento3();

        // Tabla 1
        String data[][] = {};
        String col[] = { "Nombre", "Primer apellido", "Segundo apellido", "Salario" };
        DefaultTableModel tableModel1 = new DefaultTableModel(data, col);
        jTable1 = new javax.swing.JTable(tableModel1);
        jTable1.setForeground(new java.awt.Color(102, 0, 102));
        for (Lider lider : informacionLider) {
            String nombre = lider.getNombre();
            String primerApellido = lider.getPrimer_Apellido();
            String segundoApellido = lider.getSegundo_Apellido();
            float salario = lider.getSalario();
            tableModel1.addRow(new Object[] { nombre, primerApellido, segundoApellido, salario });
        }
        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 51));
        jScrollPane1.setViewportView(jTable1);
        jTabbedPane1.addTab("Consulta 1", jScrollPane1);

        // Tabla 2
        String datosNombreLider[][] = {};
        String colNombreLider[] = { "Nombre" };
        DefaultTableModel tableModelNombreLider = new DefaultTableModel(datosNombreLider, colNombreLider);
        jTable2 = new javax.swing.JTable(tableModelNombreLider);
        for (String nombre : nombresLideres) {
            tableModelNombreLider.addRow(new Object[] { nombre });
        }
        jScrollPane2.setViewportView(jTable2);
        jTabbedPane1.addTab("Consulta 2", jScrollPane2);

        // Tabla 3
        String datosPromedioSalario[][] = {};
        String colPromedioSalario[] = { "Cargo", "Salario promedio" };
        DefaultTableModel tableModelPromedioSalario = new DefaultTableModel(datosPromedioSalario, colPromedioSalario);
        jTable3 = new javax.swing.JTable(tableModelPromedioSalario);
        for (PromedioSalario promedioSalario : promediosSalarios) {
            String cargo = promedioSalario.getCargo();
            DecimalFormat df = new DecimalFormat(".000000");
            String salario = df.format(promedioSalario.getSalarioPromedio());

            tableModelPromedioSalario.addRow(new Object[] { cargo, salario });
        }
        jScrollPane3.setViewportView(jTable3);
        jTabbedPane1.addTab("Consulta 3", jScrollPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(208, 208, 208).addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup().addContainerGap()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(291, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
